### ISSUE TITLE
Add a security policy

### ISSUE THREAD

**Issue by zidingz** [Mupati/laravel-video-chat#10]
Hey there!

I belong to an open source security research community, and a member (@0x7zed) has found an issue, but doesn’t know the best way to disclose it.

If not a hassle, might you kindly add a `SECURITY.md` file with an email, or another contact method? GitHub [recommends](https://docs.github.com/en/code-security/getting-started/adding-a-security-policy-to-your-repository) this best practice to ensure security issues are responsibly disclosed, and it would serve as a simple instruction for security researchers in the future.

Thank you for your consideration, and I look forward to hearing from you!

(cc @huntr-helper)

**Comment by Mupati** [comment]
Thanks for reaching out.
I would like to know the nature of the security flaw.
However this is a repository for hosting demo applications for the articles
I write so
I'm not sure we have a serious cause for alarm.

Best Regards,
Kofi Mupati

**Comment by Mupati** [comment]
Alright. I'll take a look and add the `SECURITY.md`

**Comment by Mupati** [comment]
I've added it.
